apiVersion: v1
kind: PersistentVolume
metadata:
  name: irods-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: irods-sc
  csi:
    driver: irods.csi.cyverse.org
    volumeHandle: irods-vol-id
    volumeAttributes:
      driver: "irodsfuse"
      host: "data.cyverse.org"
      port: "1247"
      zone: "iplant"
      user: "iychoi"
      password: "yourpassword"
      path: "/home/iychoi"
