apiVersion: v1
kind: PersistentVolume
metadata:
  name: irods-nfs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: irods-sc
  csi:
    driver: irods.csi.cyverse.org
    volumeHandle: irods-vol-id
    volumeAttributes:
      driver: "nfs"
      host: "data.cyverse.org"
      uid: "1000"
      gid: "1000"
      path: "/home/iychoi"
