apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: cyverse/irods-csi-driver
  newTag: v0.1.0
- name: quay.io/k8scsi/livenessprobe
  newTag: v2.0.0
- name: quay.io/k8scsi/csi-node-driver-registrar
  newTag: v1.3.0
