apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: cyverse/irods-csi-driver
  newTag: v0.10.14
- name: cyverse/irods-csi-driver-pool
  newTag: v0.10.14
- name: registry.k8s.io/sig-storage/csi-provisioner
  newTag: v3.1.0
- name: registry.k8s.io/sig-storage/livenessprobe
  newTag: v2.11.0
- name: registry.k8s.io/sig-storage/csi-node-driver-registrar
  newTag: v2.9.1
