apiVersion: v1
kind: Pod
metadata:
  name: irods-irodsfuse-app
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "wc -l /data/input/mrsa_mssa.fa >> /data/output/mrsa_mssa.txt && wc -l /data/input/pov.fa >> /data/output/pov.txt"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  restartPolicy: Never
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: irods-irodsfuse-pvc
