apiVersion: v1
kind: Pod
metadata:
  name: my-app # the name of the app
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "wc -l /data/input/mrsa_mssa.fa >> /data/output/mrsa_mssa.txt && wc -l /data/input/pov.fa >> /data/output/pov.txt"]
    volumeMounts:
    - name: persistent-storage # the name of the volume
      mountPath: /data # mount point
  restartPolicy: Never
  volumes:
  - name: persistent-storage # the name of the volume
    persistentVolumeClaim:
      claimName: my-pvc # the name of the PVC
