apiVersion: v1
kind: PersistentVolume
metadata:
  name: irods-irodsfuse-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: irods-sc
  csi:
    driver: irods.csi.cyverse.org
    volumeHandle: irods-irodsfuse-vol-id
    volumeAttributes:
      driver: "irodsfuse"
      host: "data.cyverse.org"
      port: "1247"
      zone: "iplant"
      path: "/home/iychoi"
    nodePublishSecretRef: 
      name: "irods-irodsfuse-secret"
      namespace: "default"
