kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "helm.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerService.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}-controller
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}-controller
    spec:
      serviceAccount: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controllerService.podSecurityContext | nindent 8 }}
      priorityClassName: system-cluster-critical
      tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
      containers:
        - name: irods-plugin
          securityContext:
            {{- toYaml .Values.controllerService.irodsPlugin.securityContext | nindent 12 }}
          image: "{{ .Values.controllerService.irodsPlugin.image.repository }}:{{ .Values.controllerService.irodsPlugin.image.tag }}"
          imagePullPolicy: {{ .Values.controllerService.irodsPlugin.image.pullPolicy }}
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeid=$(NODE_ID)
            {{- toYaml .Values.controllerService.irodsPlugin.extraArgs | nindent 12 }}
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            {{- toYaml .Values.controllerService.irodsPlugin.resources | nindent 12 }}
        - name: csi-provisioner
          image: "{{ .Values.controllerService.csiProvisioner.image.repository }}:{{ .Values.controllerService.csiProvisioner.image.tag }}"
          args:
            - --csi-address=$(ADDRESS)
            {{- toYaml .Values.controllerService.csiProvisioner.extraArgs | nindent 12 }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources:
            {{- toYaml .Values.controllerService.csiProvisioner.resources | nindent 12 }}

      volumes:
        - name: plugin-dir
          emptyDir: {}
      {{- with .Values.controllerService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
