kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "helm.fullname" . }}-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}-node
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}-node
    spec:
      securityContext:
        {{- toYaml .Values.nodeService.podSecurityContext | nindent 8 }}
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      containers:
        - name: irods-plugin
          securityContext:
            {{- toYaml .Values.nodeService.irodsPlugin.securityContext | nindent 12 }}
          image: "{{ .Values.nodeService.irodsPlugin.image.repository }}:{{ .Values.nodeService.irodsPlugin.image.tag }}"
          imagePullPolicy: {{ .Values.nodeService.irodsPlugin.image.pullPolicy }}
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeid=$(NODE_ID)
            - --secretpath=$(SECRET_VOLUME_PATH)
            - --poolservice=$(IRODSFS_POOL_ENDPOINT)
            - --prometheus_exporter_port=$(PROMETHEUS_EXPORTER_PORT)
            - --storagepath=$(STORAGE_VOLUME_PATH)
            {{- toYaml .Values.nodeService.irodsPlugin.extraArgs | nindent 12 }}
          env:
            - name: CSI_ENDPOINT
              value: unix:/csi/csi.sock
            - name: IRODSFS_POOL_ENDPOINT
              value: {{ .Values.nodeService.irodsPlugin.poolServerEndpoint }}
            - name: SECRET_VOLUME_PATH
              value: /secrets
            - name: STORAGE_VOLUME_PATH
              value: /storage
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PROMETHEUS_EXPORTER_PORT
              value: "12023"
          volumeMounts:
            - name: mountpoint-dir
              mountPath: {{ .Values.kubeletDir }}/pods
              mountPropagation: Bidirectional
            - name: plugin-dir
              mountPath: {{ .Values.kubeletDir }}/plugins
              mountPropagation: Bidirectional
            - name: socket-dir
              mountPath: /csi
            - name: secret-volume
              mountPath: /secrets
            - name: storage-volume
              mountPath: /storage
          ports:
            - containerPort: 9810
              name: healthz
              protocol: TCP
            - containerPort: 12023
              name: prom-metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          resources:
            {{- toYaml .Values.nodeService.irodsPlugin.resources | nindent 12 }}
        - name: irods-pool
          securityContext:
            {{- toYaml .Values.nodeService.irodsPool.securityContext | nindent 12 }}
          image: "{{ .Values.nodeService.irodsPool.image.repository }}:{{ .Values.nodeService.irodsPool.image.tag }}"
          imagePullPolicy: {{ .Values.nodeService.irodsPool.image.pullPolicy }}
          args:
            - --data_root=$(IRODSFS_POOL_DATA)
            - --endpoint=$(IRODSFS_POOL_ENDPOINT)
            - --prometheus_exporter_port=$(PROMETHEUS_EXPORTER_PORT)
            {{- toYaml .Values.nodeService.irodsPool.extraArgs | nindent 12 }}
          env:
            - name: IRODSFS_POOL_DATA
              value: /irodsfs_pool_data
            - name: IRODSFS_POOL_ENDPOINT
              value: {{ .Values.nodeService.irodsPool.poolServerEndpoint }}
            - name: PROMETHEUS_EXPORTER_PORT
              value: "12022"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - containerPort: 12022
              name: prom-metrics
              protocol: TCP
          resources:
            {{- toYaml .Values.nodeService.irodsPool.resources | nindent 12 }}
        - name: csi-driver-registrar
          securityContext:
            {{- toYaml .Values.nodeService.csiDriverRegistrar.securityContext | nindent 12 }}
          image: "{{ .Values.nodeService.csiDriverRegistrar.image.repository }}:{{ .Values.nodeService.csiDriverRegistrar.image.tag }}"
          imagePullPolicy: {{ .Values.nodeService.csiDriverRegistrar.image.pullPolicy }}
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            {{- toYaml .Values.nodeService.csiDriverRegistrar.extraArgs | nindent 12 }}
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ .Values.kubeletDir }}/plugins/irods.csi.cyverse.org/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources:
            {{- toYaml .Values.nodeService.csiDriverRegistrar.resources | nindent 12 }}
        - name: liveness-probe
          imagePullPolicy: {{ .Values.nodeService.livenessProbe.image.pullPolicy }}
          image: "{{ .Values.nodeService.livenessProbe.image.repository }}:{{ .Values.nodeService.livenessProbe.image.tag }}"
          args:
            - --csi-address=/csi/csi.sock
            - --health-port=9810
            - --probe-timeout=10s
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            {{- toYaml .Values.nodeService.livenessProbe.resources | nindent 12 }}
      volumes:
        - name: mountpoint-dir
          hostPath:
            path: {{ .Values.kubeletDir }}/pods
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: {{ .Values.kubeletDir }}/plugins
            type: Directory
        - name: registration-dir
          hostPath:
            path: {{ .Values.kubeletDir }}/plugins_registry
            type: Directory
        - name: socket-dir
          hostPath:
            path: {{ .Values.kubeletDir }}/plugins/irods.csi.cyverse.org
            type: DirectoryOrCreate
        - name: secret-volume
          secret:
            secretName: {{ include "helm.fullname" . }}-global-secret
        - name: storage-volume
          hostPath:
            path: {{ .Values.kubeletDir }}/plugins/irods.csi.cyverse.org/storage
            type: DirectoryOrCreate
      {{- with .Values.nodeService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}