globalConfig:
  secret:
    stringData:
      client: "irodsfuse"
      host: "data.cyverse.org"
      port: "1247"
      zone: "iplant"
      retainData: "false"
      mountPathWhitelist: "/iplant/home"

# only for k0s
kubeletDir: /var/lib/k0s/kubelet