apiVersion: v1
kind: Secret
metadata:
  # This name must match the global Secret configured for the CSI deployment.
  name: irods-csi-driver-global-secret
type: Opaque
stringData:
  client: "irodsfuse" # iRODS client
  host: "data.cyverse.org"  # iRODS host 
  port: "1247" # iRODS port
  zone: "iplant" # iRODS zone name
  # Proxy identity used to establish the iRODS connection.
  user: "rods" # iRODS proxy username
  password: "my_password" # iRODS proxy user password
  enforceProxyAccess: "true" # enforce proxy access
  mountPathWhitelist: "/iplant/home" # list of paths allowed to mount
