apiVersion: v1
kind: Pod
metadata:
  name: my-app # the name of the app
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo Hello Kubernetes! $(date -u) >> /data/irods_csi_driver_out.txt"]
    volumeMounts:
    - name: persistent-storage # the name of the volume
      mountPath: /data # mount point
  restartPolicy: Never
  volumes:
  - name: persistent-storage # the name of the volume
    persistentVolumeClaim:
      claimName: my-pvc # the name of the PVC
