apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv # the name of the pv
  labels:
    vol-name: my-pv # same as the name
spec:
  capacity:
    storage: 5Gi # this is required but not meaningful (ignored by csi driver)
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: irods-sc # the name of Storage Class
  csi:
    driver: irods.csi.cyverse.org # the name of iRODS CSI driver
    volumeHandle: my-vol-id # unique volume ID
    volumeAttributes:
      client: "nfs" # iRODS client
      host: "data.cyverse.org" # iRODS host
      path: "/home/my_username" # iRODS path to mount (this is NFS path)
