kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: irods-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: irods-plugin
          image: cyverse/irods-csi-driver:latest
          imagePullPolicy: Always
        - name: irods-pool
          image: cyverse/irods-csi-driver-pool:latest
          imagePullPolicy: Always
