apiVersion: v1
kind: PersistentVolume
metadata:
  name: irods-webdav-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: irods-sc
  csi:
    driver: irods.csi.cyverse.org
    volumeHandle: irods-webdav-vol-id
    volumeAttributes:
      client: "webdav"
      url: "https://data.cyverse.org/dav/iplant/home/iychoi"
      user: "iychoi"
      password: "yourpassword"
