apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irods-irodsfuse-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: irods-sc
  selector:
    matchLabels:
      vol-name: irods-irodsfuse-pv
  resources:
    requests:
      storage: 5Gi
