apiVersion: v1
kind: Secret
metadata:
  name: irods-csi-driver-global-secret
  namespace: kube-system
type: Opaque
stringData:
  client: "irodsfuse"
  host: "data.cyverse.org"
  port: "1247"
  zone: "iplant"
  user: "rods"
  password: "password"
  retainData: "false"
  enforceProxyAccess: "true"
  mountPathWhitelist: "/iplant/home,/iplant/shared"
  