apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: irods-sc
  resources:
    requests:
      storage: 5Gi # this is required but not meaningful
