kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: irods-sc
provisioner: irods.csi.cyverse.org
parameters:
  clientUser: "my_client_user" # iRODS proxy client username
  volumeRootPath: "/iplant/home/my_client_user" # iRODS path to create a sub-directory and mount
