apiVersion: v1
kind: Job
metadata:
  name: irods-webdav-app
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo Hello Kubernetes! $(date -u) >> /data/kubernetes_webdav_out.txt"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: irods-pvc
