apiVersion: v1
kind: PersistentVolume
metadata:
  name: irods-webdav-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: irods-sc
  csi:
    driver: irods.csi.cyverse.org
    volumeHandle: irods-vol-id
    volumeAttributes:
      driver: "webdav"
      protocol: "https"
      host: "data.cyverse.org"
      zone: "iplant"
      user: "iychoi"
      urlprefix: "dav"
      password: "yourpassword"
      path: "/home/iychoi"
